services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./volume/postgres-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
